server:
  port: 8088
  servlet:
    context-path: /wuqq
spring:
  application:
    name: mapper-producer
  datasource:
#    url: jdbc:oracle:thin:@172.20.19.29:1521:wacc
    url: jdbc:mysql://127.0.0.1:3306/mogu_blog?characterEncoding=utf8&connectTimeout=100&socketTimeout=3000&autoReconnect=true&useUnicode=true&useSSL=false&serverTimezone=UTC
    username: root
    password: 142845wer
    driver-class-name: com.mysql.cj.jdbc.Driver
rocketmq:
  group: transaction-test
  namesrv: 127.0.0.1:9876
#  消息最大长度 默认1024*4（4M）
  maxMessageSize: 4096
#  默认 3000 单位mills
  sendTimeout: 10000
#  重试次数 默认2
  retryTimes: 3

#  基本配置
  topic: transaction-topic
  tags: transaction-topic
mybatis-plus:
  mapper-locations: classpath*:/mapper/*.xml
