spring:
  profiles:
    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
      routes:
        - id: nacos-gateway
          uri: lb://nacos-gateway
          predicates:
            - Path=/nacos-gateway/**
          filters:
            - StripPrefix=1

